#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: 果凍圖片沙盒 → itch.io 上架流程（butler push）
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

banner "果凍圖片沙盒：上架 itch.io"

# ── Stage 1: 環境檢查 + 建置 ────────────────────────────────────────────────
stage "環境檢查 + 建置最新的 dist/"

if ! command -v butler >/dev/null 2>&1; then
  warn "找不到 butler，請先安裝：https://itch.io/docs/butler/installing.html"
  exit 1
fi
say "butler 版本：$(butler -V)"

BUTLER_CREDS="${HOME}/.config/itch/butler_creds"
if [[ -f "$BUTLER_CREDS" ]]; then
  say "已找到 butler 登入憑證（$BUTLER_CREDS），跳過登入。"
else
  warn "還沒登入 butler，需要先做一次 butler login。"
  step "會開一個瀏覽器分頁做 itch.io 授權。"
  pause "準備好就按 Enter 執行 butler login"
  butler login
fi

if [[ ! -f package.json ]]; then
  warn "目前目錄底下沒有 package.json——請在專案根目錄（果凍圖片專案）執行這支腳本。"
  exit 1
fi

say "執行 npm run build（型別檢查 + 產出自包含的 dist/index.html）..."
npm run build

if [[ ! -f dist/index.html ]]; then
  warn "npm run build 完成了，但沒看到 dist/index.html，停下來看看發生什麼事。"
  exit 1
fi
say "✓ dist/index.html 已產生（$(du -h dist/index.html | cut -f1)）。"
pause

# ── Stage 2: 建立或確認 itch.io 專案頁面 ────────────────────────────────────
stage "建立或確認 itch.io 專案頁面"

if confirm "已經有這個遊戲的 itch.io 專案頁面了嗎？"; then
  say "好，直接填現有專案的資訊。"
else
  say "還沒有的話，這階段帶你建立一個新專案頁面。"
  open_url "https://itch.io/game/new"
  step "Title：隨便你取一個名字（之後隨時可改）。"
  step "Project URL：這是你的 project slug，記下來，等一下要用。"
  step "Classification 選 Games。"
  step "Kind of project 一定要選 ${BOLD}HTML${RESET}——這樣 itch.io 才會用瀏覽器內嵌播放，不是當成一般檔案下載。"
  step "填完先按下面的 Save & view page 或 Create Game 存起來（細節之後隨時能改）。"
  pause "建好之後按 Enter 繼續"
fi

say "從網址列可以看到 https://<使用者名稱>.itch.io/<project-slug> 這樣的格式。"
ask ITCH_USER "你的 itch.io 使用者名稱："
ask ITCH_PROJECT "專案的 project slug："
write_env ITCH_USER "$ITCH_USER"
write_env ITCH_PROJECT "$ITCH_PROJECT"

# ── Stage 3: 決定 channel 名稱 ──────────────────────────────────────────────
stage "決定 butler channel 名稱"

say "channel 是 butler push 用來標記「這是哪一種上傳檔」的字串，慣例用 html5。"
say "之後每次更新版本都固定推同一個 channel，itch.io 會自動疊上去、不用重新設定內嵌。"
ask ITCH_CHANNEL "Channel 名稱："
if [[ -z "$ITCH_CHANNEL" ]]; then
  ITCH_CHANNEL="html5"
  say "沒填，使用預設值：html5"
fi
write_env ITCH_CHANNEL "$ITCH_CHANNEL"

ITCH_TARGET="${ITCH_USER}/${ITCH_PROJECT}:${ITCH_CHANNEL}"
write_env ITCH_TARGET "$ITCH_TARGET"
say "推送目標：$ITCH_TARGET"

# ── Stage 4: butler push ────────────────────────────────────────────────────
stage "執行 butler push"

say "即將執行：butler push dist $ITCH_TARGET"
pause "準備好就按 Enter"
if ! butler push dist "$ITCH_TARGET"; then
  warn "push 失敗。最常見原因是登入憑證過期——執行 'butler login' 後重跑這支腳本即可，"
  warn "已經填過的值都存在 .env 裡，重跑會直接帶出來（Enter 就能沿用）。"
  exit 1
fi
say "✓ push 成功。"
pause

# ── Stage 5: 編輯頁設定內嵌 ──────────────────────────────────────────────────
stage "在 itch.io 編輯頁設定瀏覽器內嵌"

open_url "https://itch.io/dashboard"
step "點進你剛剛那個專案 → 按 Edit game。"
step "捲到 Uploads 區塊，會看到一個名字包含「$ITCH_CHANNEL」的檔案（butler 剛推上去的那個）。"
step "勾選它旁邊的 \"This file will be played in the browser\"。"
step "出現的 Embed options 裡，Viewport 建議勾 \"Automatically calculate width and height\"，"
step "或手動填一個比較大的桌面尺寸（例如 1280x720）——抓/甩果凍的手感在小畫布裡會很侷促。"
step "這個 App 有做觸控手勢，想讓手機/平板玩家也能玩的話勾選 \"Mobile friendly\"。"
step "捲到最下面按 Save。"
pause "都設定完、存檔後按 Enter 繼續"

# ── Stage 6: 預覽測試 ────────────────────────────────────────────────────────
stage "預覽測試"

step "在編輯頁按右上角的 \"View page\"（或 Preview 連結）。"
step "在 itch.io 的內嵌畫面裡實際玩一輪：抓一角拖曳甩動、輕拍、開 Pin 模式放一個 Pin、切換 Boundary。"
step "打開瀏覽器 DevTools 的 Console，確認沒有紅字錯誤。"
if ! confirm "在 itch.io 內嵌畫面裡玩起來一切正常？"; then
  warn "先別急著往下——回去看 Console 錯誤或內嵌設定，修好後重跑這支腳本（會沿用已存的設定，直接跳到這裡附近）。"
  exit 1
fi

# ── Stage 7: 決定公開範圍 ────────────────────────────────────────────────────
stage "決定公開範圍"

say "itch.io 編輯頁最上面有個 Visibility 選項，通常是 Draft / Restricted / Public 三選一"
say "（實際文字可能因 itch.io 介面更新而略有不同）。"
step "建議先選 Restricted（僅限知道連結的人），自己抓連結分享給信任的人測一輪。"
pause "選好 Restricted 並存檔後按 Enter 繼續"

if confirm "要不要現在就直接切成完全公開（Public）？"; then
  step "回編輯頁把 Visibility 改成 Public，存檔。"
  pause "改完按 Enter"
  say "✓ 已設定為公開。"
else
  say "維持 Restricted——之後想公開時，回編輯頁把 Visibility 改成 Public 即可，不需要重跑這支腳本。"
fi

finish
note "頁面網址：https://${ITCH_USER}.itch.io/${ITCH_PROJECT}"
note "之後要推新版本：npm run build && butler push dist ${ITCH_TARGET}"
note "或者直接重跑這支腳本——已存的設定會自動帶出來，Enter 就能沿用。"
